server:
  port: 8082

spring:
  application:
    name: email-service
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/email_db
  mail:
    host:
    port:
    username: admin
    password: 1234
